### PR TITLE
Init project

### PR DESCRIPTION
**Pull request by CoBeKieuKy**

### CODE REVIEW

**Review by hiendt-0025 — APPROVED** [review]

**Review by huutuan2308 — APPROVED** [review]

**Comment by CoBeKieuKy** [comment]
ready

**Review by thaodtd-0665 — COMMENTED** [review]
Đính kèm link ticket vào PR

**Comment by CoBeKieuKy** [comment]
https://edu-redmine.sun-asterisk.vn/issues/27368
ready

**Comment by CoBeKieuKy** [comment]
ready

**Review by thaodtd-0665 — APPROVED** [review]

**Pull request merged**
